### PR TITLE
Feature #209: initial implementation of download authorization

### PR DESCRIPTION
**Pull request by jauhien**
This is an implementation of crate download authorization for issue #209.

In our use-case we need to restrict download of crates on per user basis (we intend to use kellnr in our private crate registry in one of the projects).

Regarding the API design I tried to follow the HTTP semantics, so PUT/DELETE operate on a given user.

Also we would need more changes regarding user management and web-hooks that I would be happy to discuss them with you.

### CODE REVIEW

**Comment by secana** [comment]
Hi @jauhien, 
sry for the late response. I had some busy weeks. First: Thanks for putting in that much work!

What do we need to discuss to get the feature working an merged?

**Comment by jauhien** [comment]
Hi @secana , the feature concerned in this MR as implemented can be merged and is working.

We would need other changes, but for now we are focused on other work, so I do not expect that we will be able to discuss them before September.

Regarding this MR I would be grateful if you could do code-review, so I can make changes based on your feed-back (if any) and the final version can be merged by you.

**Comment by secana** [comment]
A question for clarification: 
Is the introduction of a `crate_user` necessary? Wouldn't it be much easier to use the existing concept of a an `owner` and enhance it, such that it has a flag for "read" or "read/write" access? It seems to me that this would do the same with half the code.
Or do I miss something and the introduction of a `crate_user` relation has some more benefits?

**Comment by jauhien** [comment]
Sorry for a long pause: I was on vacations and then had other topics to manage.

Your comment sounds reasonable to me, so I will redo those changes and update PR.

**Comment by jauhien** [comment]
Dear @secana , I have thought a bit more and there is one thing that probably makes `crate_user` necessary: we do not want to allow crate owner with write access to be able to change crate users list as in our use case crates uploading is separated from granting access to crates.

In current implementation crate owners can change list of owners (which seems to be reasonable as there can be a necessity to pass upload authorization to other user or to revoke it).

So I can see two options: keep separated crate user entity or restrict crate owners changes to admins only.

Which option seems better to you?

**Comment by vikulikov** [comment]
@secana Hello! Is there something that is blocking this PR from merge?

**Comment by secana** [comment]
Hi, I've reviewed most of it and think it's ready to be merged. As it is a big new feature, would you be so kind and add documentation about it for https://kellnr.io? The correspondig page for docs is here: https://github.com/kellnr/website/blob/main/src/views/DocumentationV5View.vue

**Comment by jauhien** [comment]
@secana , thank you very much!

Surely, I can add the docs. I will have a look this week.

**Comment by jauhien** [comment]
@secana , sorry for a longer pause, I have created a pull request on the website repo.

Please, do not hesitate to comment if you need more documentation.

From the side of user this feature is seen as an additional settings tab (available to administrator) and as a mechanism that rejects cargo pulls for unauthorized users, so documentation is not long.

**Pull request merged**
